version: 1.0.{build}
os: Visual Studio 2015

install:
- ps: cinst innosetup

build_script:
- cd msbuild
- appveyor DownloadFile https://cdn.rawgit.com/domoticz/win32-libraries/master/WindowsLibraries.7z
- '7z x WindowsLibraries.7z > NUL:'
- cd ..
- msbuild msbuild\domoticz.sln /p:Configuration=Release /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cp appversion.h version_win32.h
- cp History.txt history_win32.txt
- '"C:\Program Files (x86)\Inno Setup 5\ISCC.exe" msbuild\WindowsInstaller\DomoticzSetup.iss'
- msbuild msbuild\package.proj

artifacts:
- path: domoticz-*-latest.zip
- path: version_win32.h
- path: history_win32.txt

test: off

deploy:
- provider: FTP
  host: 188.166.24.182
  folder: beta
  protocol: ftps
  username: uploads@domoticz.com
  password: $(FTP_PASSWORD)
  on:
    APPVEYOR_REPO_NAME: domoticz/domoticz
    APPVEYOR_REPO_BRANCH: master  

